language: rust
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
  - sudo update-alternatives --set gcc /usr/bin/gcc-7
  - sudo update-alternatives --set g++ /usr/bin/g++-7
  - sudo update-alternatives --set cc /usr/bin/gcc
  - sudo update-alternatives --set c++ /usr/bin/g++
  - export CC=gcc-7 CXX=g++-7
  - cargo clippy --all-targets --all-features -- -A clippy::module_inception -A clippy::new_without_default -A clippy::borrowed_box
  - cargo build --all
  - for crate in . task-maker-*; do
      (cd $crate && RUST_BACKTRACE=1 cargo test --all)
    done
  - rm -rf target/doc  # make sure only our crates are present
  - cargo doc --no-deps --package task-maker-rust $(CRATES=(task-maker-*) && echo ${CRATES[@]/#/--package })
  - echo '<meta http-equiv="Refresh" content="0; url=./task_maker/index.html">' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  allow_empty_commit: true
  local_dir: target/doc
  on:
    branch: master

cache: cargo
