language: rust
dist: bionic
addons:
  apt:
    packages:
      - g++
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - set -e
  - cargo clippy --all-targets --all-features -- -A clippy::module_inception -A clippy::new_without_default -A clippy::borrowed_box -A clippy::redundant_closure_call
  - cargo build --all
  - RUST_BACKTRACE=1 cargo test --all
  - rm -rf target/doc  # make sure only our crates are present
  - cargo doc --no-deps
  - echo '<meta http-equiv="Refresh" content="0; url=./task_maker/index.html">' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  allow_empty_commit: true
  local_dir: target/doc
  on:
    branch: master

cache: cargo
