language: rust
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
  - sudo update-alternatives --set gcc /usr/bin/gcc-7
  - sudo update-alternatives --set g++ /usr/bin/g++-7
  - sudo update-alternatives --set cc /usr/bin/gcc
  - sudo update-alternatives --set c++ /usr/bin/g++
  - export CC=gcc-7 CXX=g++-7
  - cargo clippy --all-targets --all-features -- -A clippy::module_inception -A clippy::new_without_default -A clippy::borrowed_box
  - cargo build --all
  - RUST_BACKTRACE=1 cargo test --all
cache: cargo
