language: rust
dist: bionic
addons:
  apt:
    packages:
      - g++
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - set -e
  - cargo clippy --color=always --all-targets --all-features -- -A clippy::too_many_arguments -A clippy::large_enum_variant
  - cargo build --color=always --all
  - RUST_BACKTRACE=1 cargo test --color=always --all
  - rm -rf target/doc  # make sure only our crates are present
  - cargo doc --color=always --no-deps --all
  - echo '<meta http-equiv="Refresh" content="0; url=./task_maker/index.html">' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  allow_empty_commit: true
  local_dir: target/doc
  on:
    branch: master

cache: cargo
