[package]
name = "task-maker-rust"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.88", features = ["derive", "rc"] }
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }
byteorder = "1"
failure = "0.1.5"
log = "0.4"
env_logger = "0.6"