[package]
name = "task-maker-rust"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = { version = "1.0.88", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
uuid = { version = "0.7", features = ["v4", "serde"] }
byteorder = "1"
failure = "0.1.5"
log = "0.4"
env_logger = "0.6"
blake2 = "0.8"
hex = "0.3"
fs2 = "0.4"
chrono = { version = "0.4", features = ["serde"] }
tempdir = "0.3"
pest = "2.1"
pest_derive = "2.1"
which = "2.0"
lazy_static = "1.3"
glob = "0.2"
boxfnonce = "0.1.1"
regex = "1"
termcolor = "1"

[dev-dependencies]
pretty_assertions = "0.6"

[build-dependencies]
glob = "0.2"

[[bin]]
name = "task-maker"
path = "src/main.rs"
