[workspace]

members = ["task-maker-*"]

[package]
name = "task-maker-rust"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"
documentation = "https://edomora97.github.io/task-maker-rust/"
repository = "https://github.com/edomora97/task-maker-rust"
license = "MPL-2.0"

[badges]
travis-ci = { repository = "edomora97/task-maker-rust" }

[dependencies]
task-maker-dag = { path = "./task-maker-dag" }
task-maker-store = { path = "./task-maker-store" }
task-maker-cache = { path = "./task-maker-cache" }
task-maker-exec = { path = "./task-maker-exec" }
task-maker-format = { path = "./task-maker-format" }
log = "0.4"
env_logger = "0.6"
tempdir = "0.3"
structopt = "0.2"
num_cpus = "1.10"

[[bin]]
name = "task-maker"
path = "src/main.rs"