[package]
name = "task-maker-format"
version = "0.3.4"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
task-maker-dag = { path = "../task-maker-dag" }
task-maker-lang = { path = "../task-maker-lang" }
task-maker-exec = { path = "../task-maker-exec" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
failure = "0.1"
itertools = "0.8"
termcolor = "1"
log = "0.4"
glob = "0.2"
pest = "2.1"
pest_derive = "2.1"
tui = "0.5"
termion = "1.5"
lazy_static = "1.3"
approx = "0.3"
regex = "1"
askama = "0.8"
askama_derive = "0.8"
mime_guess = "2.0"
rand = "0.7"

[dev-dependencies]
tempdir = "0.3"
pretty_assertions = "0.6"
spectral = "0.6"