[package]
name = "task-maker-cache"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
task-maker-dag = { path = "../task-maker-dag" }
task-maker-store = { path = "../task-maker-store" }
itertools = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
failure = "0.1"
log = "0.4"

[dev-dependencies]
tempdir = "0.3"