[package]
name = "task-maker-lang"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
task-maker-dag = { path = "../task-maker-dag" }
serde = { version = "1.0", features = ["derive", "rc"] }
regex = "1"
failure = "0.1"
lazy_static = "1.3"

[dev-dependencies]
task-maker-exec = { path = "../task-maker-exec" }
tempdir = "0.3"
spectral = "0.6"