[package]
name = "task-maker-store"
version = "0.4.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
blake2 = "0.8"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
fs2 = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
hex = "0.3"
log = "0.4"
tempdir = "0.3"

[dev-dependencies]
pretty_assertions = "0.6"