name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install & Build
        run: |
          sudo apt update
          sudo apt install -yy curl build-essential musl musl-tools python libseccomp-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup target add x86_64-unknown-linux-musl
          source $HOME/.cargo/env
          cargo install cargo-deb
          cargo deb --target x86_64-unknown-linux-musl
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "target/x86_64-unknown-linux-musl/debian/*.deb"
