name: Release

on:
  release:
    types: [created]

jobs:
  Linux:
    name: Build & Publish (Linux)
    # Ubuntu 16.04 to keep the library versions backward-compatible
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Install & Build
        run: |
          sudo apt update
          sudo apt install -yy curl build-essential python libseccomp-dev
          # dirty trick to get the correct libgcc1 version of ubuntu16.04
          sudo apt install -y --allow-downgrades libgcc1=1:6.0.1-0ubuntu1
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install cargo-deb

          export TM_DATA_DIR=/usr/share/task-maker-rust
          cargo build --bin task-maker --release
          cargo run --release --bin task-maker-gen-autocompletion
          cargo deb --no-build
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "target/debian/*.deb"

  macOS:
    name: Build & Publish (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          export version=$(grep version Cargo.toml | cut -d'"' -f 2)
          sed -i "" "s/ARCHIVE_VERSION/v$version/g" ./tools/homebrew/task-maker-rust.rb
          curl -L -o archive.tar.gz "https://github.com/edomora97/task-maker-rust/archive/v$version.tar.gz"
          export hash=$(shasum -a 256 archive.tar.gz | grep -o "[0-9a-f]*" | head -n 1)
          sed -i "" "s/ARCHIVE_SHA256/$hash/g" ./tools/homebrew/task-maker-rust.rb

          brew update
          brew install --verbose --build-bottle ./tools/homebrew/task-maker-rust.rb
          brew bottle --force-core-tap ./tools/homebrew/task-maker-rust.rb
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "*.bottle.tar.gz"