name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Publish
    # Ubuntu 16.04 to keep the library versions backward-compatible
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Install & Build
        run: |
          sudo apt update
          sudo apt install -yy curl build-essential python libseccomp-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install cargo-deb

          export TM_DATA_DIR=/usr/share/task-maker-rust
          cargo build --bin task-maker --release
          cargo deb --no-build
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "target/debian/*.deb"
